import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/common/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased h-screen flex flex-col w-full overflow-y-scroll">
        <Nav />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
